# Generated by Django 3.2.11 on 2022-06-14 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_label', models.CharField(max_length=255)),
                ('pickup_label', models.CharField(max_length=255)),
                ('destination_coordinates', models.CharField(max_length=255)),
                ('pickup_coordinates', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deriver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deriver_user', to=settings.AUTH_USER_MODEL)),
                ('requester', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requester_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rider Request',
                'verbose_name_plural': 'Rider Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
