# Generated by Django 3.2.11 on 2022-06-15 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0002_auto_20220614_0744'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverAccept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptor_driver', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_request', to=settings.AUTH_USER_MODEL)),
                ('rider_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_request_object', to='services.riderrequest')),
            ],
            options={
                'verbose_name': 'Accepted Request',
                'verbose_name_plural': 'Accepted Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
