# Generated by Django 3.2.11 on 2022-06-15 07:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0003_driveraccept'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DriverAccept',
            new_name='DriverAcceptedRequest',
        ),
    ]
